# This workflow will build a Java project with Gradle, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: dp.apps.rancher.io/containers/gradle:8-openjdk17
      options: --user root
      credentials:
        username: ${{ secrets.appco_username }}
        password: ${{ secrets.appco_token }}

    steps:
      - uses: actions/checkout@v4
     
      - name: Build with Gradle        
        run: ./gradlew build
